/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente.visao;

import cliente.vo.Cliente;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.DefaultListSelectionModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Samsung
 */
public class Home extends JFrame {

    private Cliente cliente = null;
    private cliente.controller.Login loginCtrl = null;
    private int qtdSalas;
    private cliente.controller.Home homeCtrl = null;
    private DefaultTableModel salasTabela;

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setLocation(Toolkit.getDefaultToolkit().getScreenSize().width / 2 - this.getSize().width / 2, Toolkit.getDefaultToolkit().getScreenSize().height / 2 - this.getSize().height / 2);
        salasTabela = iniciaJTable(jTableSalas);
    }

    public Home(Cliente cliente, cliente.controller.Login loginCtrl, int qtdSalas) {
        initComponents();
        setLocation(Toolkit.getDefaultToolkit().getScreenSize().width / 2 - this.getSize().width / 2, Toolkit.getDefaultToolkit().getScreenSize().height / 2 - this.getSize().height / 2);
        this.cliente = cliente;
        jLabelBemVindo.setText("Seja bem-vindo, " + cliente.getNome());
        this.loginCtrl = loginCtrl;
        this.qtdSalas = qtdSalas;

        salasTabela = iniciaJTable(jTableSalas);
        homeCtrl = new cliente.controller.Home(this, cliente, loginCtrl.getClientSocket(), salasTabela, qtdSalas);

        MouseListener mouseL = iniciaMouseListener(this);

        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        jTableSalas.addMouseListener(mouseL);
        this.addWindowListener(new WindowAdapter() {

            public void windowClosing(WindowEvent e) {
                jButtonSairActionPerformed(null);
            }
        });
    }

    private DefaultTableModel iniciaJTable(JTable table) {

        DefaultListSelectionModel selectionModel = new DefaultListSelectionModel();
        selectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        table.setSelectionModel(selectionModel);
        DefaultTableModel tableModel = (DefaultTableModel) table.getModel();

        tableModel.setColumnIdentifiers(new Object[]{"ID", "Nome", "Descrição", "Status", "Criador", "Validade"});
        tableModel.setNumRows(0);
        table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        table.getColumnModel().getColumn(0).setPreferredWidth(table.getWidth() / table.getColumnCount() - table.getWidth() / table.getColumnCount() / 2);
        table.getColumnModel().getColumn(1).setPreferredWidth(table.getWidth() / table.getColumnCount() + table.getWidth() / table.getColumnCount() / 2);
        table.getColumnModel().getColumn(2).setPreferredWidth(table.getWidth() / table.getColumnCount() + table.getWidth() / table.getColumnCount() / 3);
        table.getColumnModel().getColumn(3).setPreferredWidth(table.getWidth() / table.getColumnCount() - table.getWidth() / table.getColumnCount() / 2);
        table.getColumnModel().getColumn(4).setPreferredWidth(table.getWidth() / table.getColumnCount());
        table.getColumnModel().getColumn(5).setPreferredWidth(table.getWidth() / table.getColumnCount() + table.getWidth() / table.getColumnCount() / 2 - table.getWidth() / table.getColumnCount() / 3);
        table.setAutoscrolls(true);

        return tableModel;
    }

    @Override
    public void setVisible(boolean b) {
        super.setVisible(b); //To change body of generated methods, choose Tools | Templates.
        if(b){
            homeCtrl.setSala(null, null);
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelBemVindo = new javax.swing.JLabel();
        jButtonSair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSalas = new javax.swing.JTable();
        jButtonCriarSala = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelBemVindo.setText("Seja bem vindo, Teste!");

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jTableSalas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "null", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableSalas);

        jButtonCriarSala.setText("Criar sala");
        jButtonCriarSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCriarSalaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelBemVindo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonCriarSala)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSair)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBemVindo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSair)
                    .addComponent(jButtonCriarSala))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed

        if (loginCtrl.Deslogar()) {
            new Login().setVisible(true);
            this.dispose();
            JOptionPane.showMessageDialog(this, "Logout realizado com sucesso!",
                    "Sucesso no Logout", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao realizar o logout!\nTente novamente.",
                    "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonCriarSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCriarSalaActionPerformed
        CriaSala novaSala = new CriaSala(homeCtrl);
        novaSala.setVisible(true);

    }//GEN-LAST:event_jButtonCriarSalaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCriarSala;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabelBemVindo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSalas;
    // End of variables declaration//GEN-END:variables

    private MouseListener iniciaMouseListener(JFrame jf) {
        return new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() > 1) {
                    homeCtrl.solicitarAcessoSala((String) salasTabela.getValueAt(jTableSalas.getSelectedRow(), 0));
                }

            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        };
    }
    public cliente.controller.Home getHomeCtrl(){
        return homeCtrl;
    }

}
